### PR TITLE
Add feeds discovery links

### PR DESCRIPTION
**Pull request by nhoizey**
I had to dive into your Github repo to find the feed URL… 😕

### CODE REVIEW

**Comment by alexcarpenter** [comment]
I have been thinking about how to surface the feeds I provide. Huge thanks for taking the time to dig in and create this PR 👏

**Comment by nhoizey** [comment]
You're welcome.

I can suggest adding a page for feeds, maybe:
https://nicolas-hoizey.com/feeds/

**Comment by alexcarpenter** [comment]
@nhoizey ah, great idea. I might do that.

**Comment by nhoizey** [comment]
👍

**Pull request merged**
